name: Bug report
description: Report something that is broken or incorrect
title: "bug: "
labels: [bug]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for the report! Please include as much detail as possible.

  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: What did you observe?
    validations:
      required: true

  - type: textarea
    id: repro
    attributes:
      label: Minimal reproduction
      description: Code snippet / steps to reproduce.
      render: julia
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: What did you expect?
    validations:
      required: false

  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: Paste `versioninfo()` and any relevant package info.
      render: text
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Logs / stacktrace
      description: Paste full output or stacktrace.
      render: text
    validations:
      required: false
